# Windows sizes
SCREEN_SIZE = (800, 600)
SETTINGS_SCREEN_SIZE = (800, 400)

# Text
FONT = "Georgia"
SUBFONT = "Helvetica"
FONT_SIZE_TITLE = 70
MINI_TITLE_SIZE = 40
SUBFONT_SIZE = 20
TEXT_SIZE = 15

# Algorithms
ALGORITHM_MINIMAX = "Minimax"
ALGORITHM_ALPHA_BETA = "Alpha-Beta"
